### ISSUE TITLE
Bouncy Castle Version Conflicts with Spark 2.2's

### ISSUE THREAD

**Issue by omervk** [ZuInnoTe/hadoopcryptoledger#37]
Spark 2.2+ transitively requires BC version 1.51 which conflicts with 1.58 required by `inputformat`. I would suggest 1.58 is shaded and assembled into the JAR to avoid this issue (if possible).

Reference: https://github.com/ZuInnoTe/spark-hadoopcryptoledger-ds/issues/9

**Comment by jornfranke** [comment]
I will investigate.

Can you please also open an issue with Apache Spark. It is not recommended to use such old versions of Bouncy Castle.

**Comment by omervk** [comment]
We already have, at the source of the issue. https://bitbucket.org/jmurty/jets3t/issues/242/bouncycastle-dependency

**Comment by jornfranke** [comment]
ah ok thank you. Do you depend on this library? Can you use an alternative way to access S3? then you could simply exclude the dependency (I am not sure if it is even needed if you have the Hadoop S3a libraries). 

Shading causes a lot of troubles with BC and I am not sure it should be like this - at least not in the inputformat, because there it is just a provided dependency. 

You can shade it in your own application. If you want then I can create a wiki entry about it to address this issue.

**Comment by jornfranke** [comment]
Btw. did you raise the issue also with the Spark team? because they would need to upgrade to a newer version of this library as well....

**Comment by omervk** [comment]
That's a good idea. We'll do that and reference the issue here.

**Comment by jornfranke** [comment]
did you have the time to do it? or should i do it?

thank you

**Comment by liorregev** [comment]
I did, they have resolved it already, for Spark 2.3.0 unfortunately
https://issues.apache.org/jira/browse/SPARK-22634

**Comment by jornfranke** [comment]
Ok then one can shard in the Spark application for Spark 2.2

**Comment by jornfranke** [comment]
i close this with the recommendation to move to Spark 2.3.0 at least.
