### ISSUE TITLE
BUILD.md - how to build source from scratch?

### ISSUE THREAD

**Issue by rounsavall** [ZuInnoTe/hadoopcryptoledger#60]
Do you have instructions on how to build hadoopcryptoledger from source, without pre-built components?

**Comment by jornfranke** [comment]
Yes it is in the wiki
https://github.com/ZuInnoTe/hadoopcryptoledger/wiki

**Comment by jornfranke** [comment]
Is the information there sufficient? Is the format as Wiki acceptable?

**Comment by rounsavall** [comment]
Thanks Jörn,

There are instructions on individual projects on how to build with gradle, but all of these depend on prebuilt components from this repo in maven. For example, I have seen:

> Could not resolve all files for configuration ':hiveudf:runtime'.
   > Could not find com.github.zuinnote:hadoopcryptoledger-fileformat:1.2.0.
     Searched in the following locations: …

I am also seeing 
> Could not resolve all files for configuration ':hiveudf:provided'.
    > Could not find org.pentaho:pentaho-aggdesigner-algorithm:5.1.5-jhyde.
    Searched in the following locations: ...

I wanted to understand how to just build everything locally with only the apache Hadoop MR, Flink and Spark pre-builts from maven repos. As well as which versions of the pre-built libraries need to be in the maven repos

**Comment by jornfranke** [comment]
There is no problem to achieve what you want. You can build the input format and publish it to a local repo, then use the other projects and they will take the dependency from the local maven repository (or an remote repository). There is even no need to change the build files in the case of a full local repository. The instructions exactly describe this and others have followed them.

However maybe your problem is not clear to me.

**Comment by rounsavall** [comment]
I figured it out. I essentially have to force download of the local maven repo with all these libraries that the gradle scripts miss so that they get picked up. 

The gradle scripts only really work once that repo is locally available. 

The scripts as written assume one already has prebuilt binaries available from public maven repo.

**Comment by rounsavall** [comment]
It would be good to hook in a step to populate the local maven repo.

**Comment by jornfranke** [comment]
Hmm, I am not sure why this was necessary for you, because all others so
far could publish a changed hadoopcryptoledger library the local Maven
repository with the instructions provided. In fact, this is how changes are
implemented and tested. Maybe you can elaborate what you mean by "populate
local Maven repository".
